### ISSUE TITLE
Camera failing to initialize with ROS2 container

### ISSUE THREAD

**Issue by matlabbe** [luxonis/rae-ros#38]
Like in #35, I can see the camera streams using robothub and the default app. However, when I tried the ROS2 container following instructions of this repo, the cameras will always fail. The error log is slightly different than #35, so it is why I report here. To better see the log, I only start the camera launch (but I see same errors with the robot bringup launch).

Steps:
1. Connect to robot with usb:
   ```
   ssh root@192.168.197.55
   ```
1. Disable robothub
   ```
   $ robothub-ctl startup disable
   ```

3. Reboot RAE, and make sure with `top` that nothing is running on the robot
   ![Screenshot from 2023-10-18 09-03-19](https://github.com/luxonis/rae-ros/assets/2319645/b86bfea0-3c0d-48a1-a230-eccf7110f3c8)

4. Reconnect to local wifi (assuming the robot was previously configured with robothub/qr code approach):
   ```
   $ systemctl stop wifi && wpa_supplicant -i wlp1s0 -c /etc/wpa_supplicant.conf & systemctl restart systemd-networkd
   ```

5. Download latest docker image (a63967bc5f82, 2 days ago):
   ```
   $ docker pull luxonis/rae-ros-robot:humble
   ```

6. Start container:
   ```
   $ docker run -it --restart=unless-stopped -v /dev/:/dev/ -v /sys/:/sys/ --privileged  --net=host luxonis/rae-ros-robot:humble
   /ws/src/rae-ros/entrypoint.sh: line 5: echo: write error: Device or resource busy
   -> /
   ```
7. Start only camera for test:
   ```
   -> / ros2 launch rae_camera rae_camera.launch.py
   ```

Log: 
```
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-10-18-15-47-49-398368-keembay-156
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [168]
[component_container-1] [INFO] [1697644070.986288703] [rae_container]: Load Library: /underlay_ws/install/depthai_ros_driver/lib/libdepthai_ros_driver.so
[component_container-1] [INFO] [1697644072.029058387] [rae_container]: Found class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
[component_container-1] [INFO] [1697644072.029274848] [rae_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
[component_container-1] [INFO] [1697644072.055533534] [rae]: No ip/mxid specified, connecting to the next available device.
[component_container-1] [2023-10-18 15:47:52.068] [depthai] [warning] USB protocol not available - If running in a container, make sure that the following is set: "-v /dev/bus/usb:/dev/bus/usb --device-cgroup-rule='c 189:* rmw'"
[component_container-1] [INFO] [1697644077.884005258] [rae]: Camera with MXID: xlinkserver and Name: 127.0.0.1 connected!
[component_container-1] [INFO] [1697644077.884234469] [rae]: PoE camera detected. Consider enabling low bandwidth for specific image topics (see readme).
[component_container-1] [INFO] [1697644077.893835626] [rae]: Device type: RAE
[component_container-1] [INFO] [1697644078.156217029] [rae]: Pipeline type: rae
[component_container-1] [INFO] [1697644079.100704689] [rae]: Finished setting up pipeline.
[component_container-1] [ERROR] [1697644079.262288597] [rae]: No calibration! Publishing empty camera_info.
[component_container-1] [ERROR] [1697644079.420786717] [rae]: No calibration! Publishing empty camera_info.
[component_container-1] [2023-10-18 15:48:02.889] [warning] FW crashed - trying to get out the core dump
[INFO] [launch.user]: Resetting PWM.
[INFO] [busybox devmem 0x20320180 32 0x00000000-2]: process started with pid [197]
[INFO] [busybox devmem 0x20320180 32 0x00000000-2]: process has finished cleanly [pid 197]
[component_container-1] [2023-10-18 15:48:05.890] [warning] Getting the core dump out - this can take up to a minute, because it first needs to be compressed.
[component_container-1] [2023-10-18 15:48:08.753] [warning] Core dump found - trying to save it
[component_container-1] [2023-10-18 15:48:08.771] [warning] Core dump saved to /tmp/depthai_J7BfO4/6BD2C816838860C5-core_dump_0.0.1+b9d342d16512608533d8b45ea79c0a11b327eeca_20231018_154805.tar.gz - please report to developers
[component_container-1] [ERROR] [1697644088.789754621] [rae_container]: Component constructor threw an exception: There is no Camera data available corresponding to the the requested source cameraId
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'rae' of type 'depthai_ros_driver::Camera' in container '/rae_container': Component constructor threw an exception: There is no Camera data available corresponding to the the requested source cameraId
```

In contrast to #35, we see here "No calibration! Publishing empty camera_info.", maybe it is with it is crashing afterwards. However I thought that the robot was factory calibrated (I unboxed the robot 2 days ago), should we recalibrate the robot?

EDIT: Attached the core dump logs
[core_dump_log.tar.gz](https://github.com/luxonis/rae-ros/files/13031040/core_dump_log.tar.gz)

**Comment by danilo-pejovic** [comment]
Yea, crashing is happening because robot is not factory calibrated. Recalibrating the roboth should help. 

```
apt update
apt install neovim libgl1-mesa-glx python3-pip
git clone --branch rvc3_calibration https://github.com/luxonis/depthai.git
cd depthai/
python3 install_requirements.py
# To calibrate rae's front cameras - for back cameras we would change the board name to "RAE-D-E"
python3 calibrate.py -s <size>  -nx <squares_X> -ny <squares_Y> -brd RAE-A-B-C -cd 1 -c 3
```

If you are having issues with RGB camera it could be helpful to install following version of depthai 

`sudo pip install --force-reinstall --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/ depthai==2.22.0.0.dev+4924831a31eea390e1e61c90e908afd309767925`

**Comment by matlabbe** [comment]
I could not calibrate the RGB camera, but I need only the stereo cameras for now, so I added option `-dsb rgb` (tried `2.22.0.0.dev+4924831a31eea390e1e61c90e908afd309767925` but same thing):
![Screenshot from 2023-10-20 18-39-38](https://github.com/luxonis/rae-ros/assets/2319645/386d159e-bd69-42fc-8456-d36250ef476c)

To avoid some python modules missing (`--recursive` during clone or `git submodule update --init`):
```
git clone --branch rvc3_calibration --recursive https://github.com/luxonis/depthai.git
```

Note also that the [Calibration](https://github.com/luxonis/rae-ros#calibration) section in README is slightly misleading: 
 * We cannot do "Within the docker image", the docker image is arm64, cannot work on desktop ubuntu x64, so just do the instructions directly on your desktop computer
 * I thought with "Within the docker image" that it can be done on the robot, but it is not possible because you need a display. If the robot is connected through USB port, the `calibrate.py` script should be able to find the cameras automatically from the desktop computer. 

For calibration, if your charuco board needs different aruco dictionary, there is no option in `calibrate.py` to change it. We should hard-code the dictionary [here](https://github.com/luxonis/depthai/blob/65fc1c6ad7495929c0f58897067af2d88f62f0f8/calibrate.py#L357C9-L358C1) and [here](https://github.com/luxonis/depthai-calibration/blob/524952bc0de2f1b9d9bb19327f6fdfa1ace7a8a2/calibration_utils.py#L108). For my own reference:
```bash
python3 calibrate.py -s 6 -ms 4.7  -brd RAE-A-B-C -cd 1 -c 3 -dsb rgb -nx 12 -ny 9
python3 calibrate.py -s 6 -ms 4.7  -brd RAE-D-E -cd 1 -c 3 -dsb rgb -nx 12 -ny 9
```
