### ISSUE TITLE
how to install robothub_core?

### ISSUE THREAD

**Issue by Alu-XXX** [luxonis/rae-ros#55]
i pull the official image luxonis/rae-ros-robot:humble, but can't find the robothub_core package, and can't install it by pip.

**Comment by Serafadam** [comment]
Hi, are you developing your robot via robothub, or locally?

**Comment by Alu-XXX** [comment]
> Hi, are you developing your robot via robothub, or locally?

via robothub right now, and also can't use this package locally.

**Comment by Alex-debug41** [comment]
![1701250284078](https://github.com/luxonis/rae-ros/assets/57550280/c9857430-ee0d-413d-8f6b-21e948989d7d)

**Comment by Alu-XXX** [comment]
> Hi, are you developing your robot via robothub, or locally?

![1701250284078](https://github.com/luxonis/rae-ros/assets/57550280/c04b4f97-f08f-4043-9ed6-f6d406b7c757)
here is the output i got
