### ISSUE TITLE
can not connect to the rae robot when i running an app 

### ISSUE THREAD

**Issue by Alu-XXX** [luxonis/rae-ros#57]
![6afffcde6da8046ad6557d240450119](https://github.com/luxonis/rae-ros/assets/57550280/4faa8b09-878f-4ff0-816f-2b2f91a6fb5f)

**Comment by Alu-XXX** [comment]
i was running an app via robothub studio, and few seconds later it couldn't connect to the rae robot. Above is the output i get

**Comment by danilo-pejovic** [comment]
Hey, sorry I missed this issue before. Is this still relevant?

**Comment by Alu-XXX** [comment]
no, thx for reply
